### ISSUE TITLE
Is this library still alive?

### ISSUE THREAD

**Issue by manuelmazzuola** [typicode/fetchival#14]
I've not seen recent updates and there are plenty of interesting pull requests to merge.

**Comment by typicode** [comment]
Hi @manuelmazzuola 

Sorry for the lack of feedback. Unfortunately, I don't have much time for this project so it's not actively maintained.

Also I don't plan to add a lot more functionality because I want to keep it a microlib and there are already other more powerful alternatives out there.

That said I'll try to have a look at the PR this week. But feel free to fork it if you want.

**Comment by manuelmazzuola** [comment]
Ok, thank you for your time @typicode  :+1:
